Traceback (most recent call last):
  File "/home/emcj/self-citation-stat.py", line 43, in <module>
    compute_self_citation_stats(full_path, self_path)
  File "/home/emcj/self-citation-stat.py", line 5, in compute_self_citation_stats
    df_all = pd.read_csv(full_path)
  File "/home/emcj/miniconda3/envs/myenv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/emcj/miniconda3/envs/myenv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/emcj/miniconda3/envs/myenv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/emcj/miniconda3/envs/myenv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/home/emcj/miniconda3/envs/myenv/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'Physics_Author_Citations_random_sample_Genderized.csv'
